---
title: "PCOSP"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Run the script

## 1. Build the PCOSP model

```{r build_and_select_models}
library(PCOSP)
```

```{r load_data}
load(file.path("..", "data", "trainingCohorts.rda"))
```

```{r train_model}
# Set seed for calculation (using old R < 3.6 RNG)
set.seed(1987, sample.kind="Rounding")

# Build the models using the selected random seed
system.time({
selectedModels <- buildPCOSPmodels(trainingCohorts, numModels=1000, nthread=15)
})
```

## 2. Calculate and Validate Meta-Estimate Statistics

```{r calculate_stats}
load(file.path("..", "data", "validationCohorts.rda"))

# Select the validation cohorts we want to include
include <- c("TCGA", "PCSI", "Kirby", "ICGC_arr", "UNC", "Chen", "OUH",
             "Zhang", "Winter", "Collisson")

# Subset to selected cohorts
validationCohorts <- validationCohorts[include]

# Fix names to look nice
names(validationCohorts) <- gsub("_arr", "-array", names(validationCohorts))

# Identify which cohorts contain sequencing data
seqCohorts <- c("PCSI", "TCGA", "Kirby")

# Calculate your validation statistics
system.time({
        validationStats <- calculateValidationStats(validationCohorts,
                                            selectedModels,
                                            seqCohorts=seqCohorts,
                                            nthread=15)
})
```

### forestPlotMetaEstimates

```{r forest_plots}
forestPlotMetaEstimate(validationStats,
                       stat="dIndex",
                       isSummary=c(rep(FALSE, 10), rep(TRUE, 3)))
```


```{r forest_plot_cIndex}
forestPlotMetaEstimate(validationStats,
                       stat="cIndex",
                       isSummary=c(rep(FALSE, 10), rep(TRUE, 3)))
```

### Calculate AUC Distribution and Plot ROC Curves

```{r}
aucStats <- aucMetaEstimates(validationCohorts, validationStats, 
                            seqCohorts=seqCohorts)
```

```{r plot_ROC_curve}
formattedValCohorts <- formatValidationCohorts(validationCohorts)
PCOSPscores <- validationStats$probabilities
colours <- c("chartreuse3", "magenta", "#fb9a99", "turquoise3", "darkgoldenrod1",
             "wheat4", "green", "red", "cornflowerblue", "mediumorchid2")

plotROCcurves(formattedValCohorts, PCOSPscores, colours)
```

## 3. Model Random Label Shuffling

```{r 3_model_random_label_shuffling}
set.seed(1987, sample.kind="Rounding")

system.time({
    randomLabelModels <- buildRandomLabelShufflingModel(trainingCohorts, 
                                                    numModels=1000, nthread=15)
})
```

```{r density_plot}

densityPlotModel(formattedValCohorts, selectedModels=randomLabelModels, seqCohorts, 
                 vlines=c(0.69, 0.72, 0.70), nthread=15)
```

## 4. Random Gene Assignment Model

```{r 4_random_gene_assignment_models}
set.seed(1987, sample.kind="Rounding")

## These results will differ from the Code Ocean capsule due to sampling.
## For the original results use: original = TRUE; this will be about 10x slower
##     than the new method.
system.time({
    randomGeneModels1 <- buildRandomGeneAssignmentModels(trainingCohorts, 
                                                         numModels=1000,
                                                         nthread=15,
                                                         original=FALSE)
})
```

```{r random_gene_assignment_density}
densityPlotModel(formattedValCohorts, selectedModels=randomGeneModels1, seqCohorts, 
                 vlines=c(0.69, 0.72, 0.70), nthread=15)
```

## 5. HyperGSA Pathway Analysis

```{r hyper_gsea_models}

dataDir <- file.path("..", "data")
pathwayDataDir <- file.path(dataDir, "Pathway_db_files")
referenceGenes <- read.table(file.path(pathwayDataDir, "reference_genes.txt"))[, 1]
PCOSPgenes <- read.table(file.path(pathwayDataDir, "pcosp_genes.txt"))[, 1]

GSCfiles <- c("hallmark.h.all.v6.1.symbols.gmt",
              "canonical.c2.cp.v6.1.symbols.gmt",
              "GOmolecular.c5.mf.v6.1.symbols.gmt",
              "GOcellular.c5.cc.v6.1.symbols.gmt")

GSCpaths <- vapply(GSCfiles, 
                   function(file, pathwayDataDir) file.path(pathwayDataDir, file),
                   pathwayDataDir,
                   FUN.VALUE=character(1))

results <- lapply(GSCpaths,
                  function(filePath, PCOSPgenes, referenceGenes, adjMethod) 
                      fitGSAtoGeneSetCollection(filePath=filePath, 
                                                 PCOSPgenes=PCOSPgenes, 
                                                 referenceGenes=referenceGenes,
                                                 adjMethod=adjMethod),
                  PCOSPgenes=PCOSPgenes,
                  referenceGenes=referenceGenes,
                  adjMethod="fdr"
                  )
names(results) <- gsub("\\..*", "", GSCfiles)
names(results)
```

```{r clinical_model_comparison}
load(file.path(dataDir, "clinicalFeatures.rda"))
load(file.path(dataDir, "cohortClasses.rda"))

# Rename clinical features for plots and reorder them
names(clinicalFeatures) <- c("PCSI", "ICGCclinical", "TCGA", "ICGCarray", "OUH")
clinicalFeatures <- clinicalFeatures[c("PCSI", "TCGA", "ICGCarray", "OUH", "ICGCclinical")]

fitClinicalModels <- summarizeClinicalModels(clinicalFeatures, cohorts=c("ICGCclinical"))

ICGCclinicalModel <- fitClinicalModels$ICGCclinical

resultsDir <- file.path("..", "results")
#save(tcgaModel$tcga$model, file=file.path(resultsDir, "TCGAclinicalModel.rda"))
```


```{r }
cohorts <- c("PCSI", "TCGA", "ICGCarray", "OUH")

modelComparisonStats <- compareClinicalModels(clinicalFeatures, cohortClasses,
                                   models="ICGCclinical",
                      cohorts=cohorts)
```

```{r barplot_model_comparison}
barplotModelComparison(modelComparisonStats, model="ICGCclinical",
                 names=c("TCGA","PCSI","ICGCarray","OUH"),
                 colours=c("palevioletred1", "darkgrey"))
```

```{r }
modelComparisonPvals <- metaEstimateComparisonAUCs(modelComparisonStats,
                                                   model="ICGCclinical",
                                                   seqCohorts=c("PCSI", "TCGA"))
modelComparisonPvals
```

```{r clinical_model_dindex_cindex}

clinicalFeatures <- clinicalFeatures[grepl(paste(cohorts, collapse="|"), names(clinicalFeatures))]
names(clinicalFeatures) <- cohorts

modelProbabilities <- calculateCohortProbabilties(fitClinicalModels, clinicalFeatures)

clinicalModelStats <- calculateModelDandCindex(modelProbabilities, 
                                               clinicalFeatures,
                                               seqCohorts=c("PCSI", "TCGA"),
                                               model="ICGCclinical")
```

```{r model_comparison_forest_plot_dindex}
forestPlotModelComparision(clinicalModelStats, 
                           stat="dIndex",
                           isSummary=c(rep(FALSE, 4), rep(TRUE, 3)))
```


```{r model_comparison_forest_plot_cindex}
forestPlotModelComparision(clinicalModelStats, 
                           stat="cIndex", 
                           isSummary=c(rep(FALSE, 4), rep(TRUE, 3)))
```

## 8. Existing Classifier Score Calculations

```{r existing_classifier_forest_plots}
dataDir <- file.path("..", "data")
classifierDir <- file.path(dataDir, "Classifier_Comparison")

# Haider data (provided by author)
load(file.path(dataDir, "haiderSigScores.rda"))

# Harmonize case/format of names to use for subsetting the list
names(haiderSigScores) <- gsub("-.*|_.*", "", tolower(names(haiderSigScores)))
    

# Birnbaum data
fileNames1 <- list.files(file.path(classifierDir, "Birnbaum"))[-1]
geneCoefFile1 <-  list.files(file.path(classifierDir, "Birnbaum"))[1]

birnbaumSigScores <- readGenefuFilesToSigScores(file.path(classifierDir, "Birnbaum"), 
                                     fileNames1, 
                                     geneCoefFile1)

# Chen data
fileNames2 <- list.files(file.path(classifierDir, "Chen"))[-1]
geneCoefFile2 <- list.files(file.path(classifierDir, "Chen"))[1]

chenSigScores <- readGenefuFilesToSigScores(file.path(classifierDir, "Chen"), 
                                            fileNames2, 
                                            geneCoefFile2, 
                                            signed=TRUE)

# PCOSP data
PCOSPscores <- validationStats$probabilities

# Harmonize case/format of names to use for subsetting the list
names(PCOSPscores) <- gsub("-.*|_.*", "", tolower(names(PCOSPscores)))
```

## 9. Existing Classifier Forestplots

```{r }
validationCohorts <- lapply(validationCohorts, function(cohort) as.data.frame(cohort, row.names=rownames(cohort)))

# Get cohort survival data
cohortSurvivalData <- lapply(validationCohorts, 
                             function(cohort) {
                                 OS <- as.numeric.factor(cohort$OS)
                                 OS_Status <- as.numeric.factor(cohort$OS_Status)
                                 data.frame("OS"=OS, "OS_Status"=OS_Status,
                                     row.names=rownames(cohort))
                                 })
# Fix TCGA data to match study files?
PCOSPscores$tcga <- PCOSPscores$tcga[cohortSurvivalData$TCGA$OS > 180]
cohortSurvivalData$TCGA <- cohortSurvivalData$TCGA[cohortSurvivalData$TCGA$OS > 180, ]

# Harmonize case/format of names to use for subsetting the list
names(cohortSurvivalData) <- gsub("-.*|_.*", "", tolower(names(cohortSurvivalData)))

cohortSurvivalData <- cohortSurvivalData[names(haiderSigScores)]

# Put our classifier data into a list
metaestimateData <- list("haider"=haiderSigScores, "chen"=chenSigScores, "birnbaum"=birnbaumSigScores, 
                         "pcosp"=PCOSPscores, "survival"=cohortSurvivalData)

# Subset cohorts/samples, reorder to match 
metaestimateData <- subsetSharedCohortsAndSamples(metaestimateData)

seqCohorts <- c("tcga", "pcsi", "kirby")

classifierStats <- lapply(metaestimateData[names(metaestimateData) != "survival"],
                          constructMetaEstimatesDF,
                          cohortData=metaestimateData[["survival"]],
                          seqCohorts=seqCohorts,
                          hetero=rep(TRUE, 3))
```

```{r classifier_forest_plot_c_index}
    forestClassifierModelComparision(classifierStats, "cIndex", 
                                names=c("Haider, 2014", "Chen, 2015", "Birnbaum, 2017", "PCOSP"))
```

```{r classifier_forest_plot_d_index}
forestClassifierModelComparision(classifierStats, "dIndex", 
                                names=c("Haider, 2014", "Chen, 2015", "Birnbaum, 2017", "PCOSP"))
```
```

## 10. Subtype Specific 

```{r }

```

